name: Next.js Deploy to Vercel

on:
  push:
    branches:
      - production
      - preview
      

jobs:
  deploy:
    runs-on: ubuntu-latestgit

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Vercel CLI
        run: npm install -g vercel

      # ðŸ”¹ Debug step to check the branch and environment
      - name: Debug branch info
        run: |
          echo "Branch detected: $GITHUB_REF"
          echo "Workflow triggered by actor: $GITHUB_ACTOR"

      - name: Deploy to Vercel
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            echo "Deploying to production..."
            vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            echo "Deploying to preview..."
            vercel --token=${{ secrets.VERCEL_TOKEN }}
          fi
